### ISSUE TITLE
Solax direct integration

### ISSUE THREAD

**Issue by stapetz** [GitHobi/solax#1]
Hi,

the solution looks quite pretty.
The Solar SK-SU5000E has the same API. And: the API is not only callable via the wlan from the inverter: if the Solax is integrated into the local network it can be opened by the internal network address (at my network: http://192.168.178.55/api/realTimeData.html) with the same result.

It would be nice if it would be possible to define a device like

define MySolax SolaxDirect 192.168.178.55 80

so that it would be possible to enter the URL / IP and the port while defining the device.

And: it would be great to have a small documentation how to install the packages and how to configure them.

I am not the best programmer, but I would like to support this module while testing it or helping to improve it. Maybe it could be a general module in them in future?

Best regards,
Stefan

**Comment by GitHobi** [comment]
Hi Stefan!
I did not expect that anyone but me could find this module useful :)
I can look into making the URL / IP configurable - should not be a big deal.
If you want to use it, you can simply download the file from github and adjust the IP in line 275.
For installation all you need to do is to copy 74_SolaxDirect.pm into the "FHEM" folder of your installation.
Restart FHEM, Then you should be able to configure the module with "define MySolax SolaxDirect"

Cheers
Hobi

**Comment by stapetz** [comment]
Hi Hobi,

thanks for the quick response.

Within the FHEM Forum there are Dome Solax Users. Some call the API from Solax Portal. But those values are updated only every five minutes.

I want to do things with the real time data.

Viele Grüsse,
Stefan Apetz

**Comment by GitHobi** [comment]
Servus.
I've update the 74_SolaxDirect.pm module ... you can now specify IP and port of your inverter.
The repository page got also some information on how to install, etc.
Hope that's useful.

**Comment by stapetz** [comment]
Hallo Hobi,

läuft prima.

Mir ist aufgefallen, dass der Wert für 
inverter_yield_month
6094.4

bei mir den Wert für die Gesamterzeugung hat und nicht für den Monat.

Auf https://community.home-assistant.io/t/solax-hybrid-inverter/22123/19 sind die Werte wie folgt beschrieben:

This is an overview of the known data fields:
Datafield:Description
0:PV1 Current
1:PV2 Current
2:PV1 Voltage
3:PV2 Voltage
4:Grid Current
5:Grid Voltage
6:Grid Power
7:Inner Temp
8:Solar Today
9:Solar Total
10:Feed In Power
11:PV1 Power
12:PV2 Power
13:Battery Voltage
14:Battery Current
15:Battery Power
16:Battery Temp
17
18:Battery Capacity
19:Solar Total 2
20
…
40
41:Energy to Grid
42:Energy from Grid
43
…
49
50:Grid Frequency
51
52
53:EPS Voltage
54:EPS Current
55:EPS VA
56:EPS Frequency


Es wäre super, wenn das Modul direkt ins FHEM Git mit einfließen könnte und direkter Bestandteil werden könnte.


Liebe Grüße,
Stefan

**Comment by GitHobi** [comment]
Cool, die Liste kannte ich noch gar nicht ... Es kann gut sein, dass bei mir da Werte falsch zugeordnet sind. Ich habe die Zuordnung mehr oder weniger geraten. 
Ich kann mal schauen ob ich denen in Fhem einen Pull Request schicken kann.

**Comment by stapetz** [comment]
Hallo Hobi,

hattest Du eigentlich den Pull Request zu fhem geschickt, so dass das dort Standardbestandteil wird?

Ferner: hattest Du mal einen Abgleich mit der Liste gemacht mit den Data Values, die ich dir in meinem letzten Post geschrieben hatte? Wie gesagt: ich meine der Wert inverter_yield_month ist nicht richtig. Das müsste der Wert für die Jahresmenge sein, nicht wie von Dir angegeben für einen Monat.

Ansonsten läuft das Modul echt super. Ich habe da jetzt eine schicke Oberfläche mit ftui mit Hilfe von fuip gemacht. Kann sich mittlerweile echt sehen lassen.

Planst Du noch irgendwelche Weiterentwicklungen?

Liebe Grüße,
Stefan
