### ISSUE TITLE
Failed login attempt

### ISSUE THREAD

**Issue by averter** [GitHobi/solax#2]
Hi,

Thanks for building up this wiki. It is most helpful. I have a similar inverter to the one you described (a solax hybrid X3 10.0T) and am just trying to get available readings on my browser by connecting to the solax. I have the solax IP address, but when I try to add to it the extension "/api/realTimeData.htm" I am met with a login page, which should accept username/password as admin. However after entering these nothing happens and I get the login page once again :-(. Do you have any idea of what I might be doing wrong? Thanks in advance.

**Comment by GitHobi** [comment]
Sorry, I think I cannot be of any help here.
I would first try to connect the normal configuration page (for me it is at http://11.11.11.1) - and verify that you can logon on to that page. If that works, try the "realTimeData.htm" page. 
If this does not work, they might have changed the interface.

**Comment by averter** [comment]
Thanks for your quick reply. I have tried (my IP is http://192.168.1.67) and cannot logon to that page. Apparently the only way to access my inverter is 1- by connecting to its wi-fi; 2- going to http://5.8.8.8; 3- giving the admin admin as user/pass. I am now trying to use a yaml script ([this](https://community.home-assistant.io/t/solax-hybrid-inverter/22123) post) to see if it works. Alternatively, I am going to try to force another static IP to the solax. I will post here any relevant results for other people on the same errand.
