### ISSUE TITLE
Anpassungen widget_solax.js

### ISSUE THREAD

**Issue by stapetz** [GitHobi/solax#3]
Hi Hobi,

ich habe nun schon sehr lange die Solax Kopplung im Einsatz und auch dein widget in ftui eingebunden. Das sieht super aus und läuft wunderbar.

Ich habe jetzt eine zweite Anlage bekommen. Nun habe ich ein Dummy Device virtualSolar erstellt und schreibe per notify summierte Werte in die Readings (z.B. battery_charge, battery_power, ...), halt die Werte, die in deinem Widget dargestellt werden.

Wenn ich aber nun deinem Widget sage, nimm bitte das virtuelle Device, also:

<div align="center" class="content" data-type="solax" data-device='virtualSolar' ></div>

dann bekomme ich nur widget_solar.js:135 Json Parse Errors zurück.

Ich finde nicht woran es liegt.

In deinem Widget verwendest du ja (scheinbar) die Variablen aus der pm Datei

my $batteryPower = $hash->{SolaxDirect}->{battery_power};
my $batteryPercent = $hash->{SolaxDirect}->{battery_remain_capacity};
my $inverter_powerexported = $hash->{SolaxDirect}->{grid_feed_in_power};
my $solar_power = $hash->{SolaxDirect}->{pv_total_power};
my $powerHouse = $hash->{SolaxDirect}->{home_power};

In meiner virtuellen Solaranlage schreibe ich genau diese Werte wieder rein. Das Widget zieht die Daten aber scheinbar nicht. Und da wo eigentlich die Uhrzeit stehen sollte (über dem Bild mit der Anlage, dem Haus etc.) steht nur eine komische ID.

Das Grafische Widget an sich ist klasse. Toll wäre eine kleine Doku, wie man das ggf. mit einem Dummy Device ansprechen kann.

Sprich: welche Readings müssen in jedem Fall da sein und wo kommt bspw. die Uhrzeit her etc.

Ich hätte gerne ein persönliche Nachricht gefunden, bin aber scheinbar zu blöd das hier in GitHub zu finden.

Also: falls du hier noch aktiv bist und das lesen solltest: ich würde mich über einen Austausch freuen ;-)

**Comment by GitHobi** [comment]
Hallo,
ich habe bei mir kein FHEM mehr laufen, daher kann ich da leider nur noch bedingt helfen. 
Wenn du in Zeile 135 einen Json Parse Error bekommst würde ich mal vermuten, dass das die Daten, die mein Modul zurück gibt "falsch" sind. Vermutlich fehlen irgendwelche Daten, die das Widget zwar nicht benötigt, die aber die Json Struktur kaputt machen. 

Ruf in FHEM mal "get virtualSolar json" auf ... das sollte dir eine korrekte Json Struktur liefern. 
Du kannst auch in widget_solax.js mal die Zeile 133 einkommentieren - dann sollte in der Console (Developer Tools vom Browser), das Json ausgegeben werden.

Wie gesagt, ich würde spontan vermuten, dass dein virtuelles Device einen Wert nicht bereitstellt und daher das Json "kaputt" ist (z.B. zwei Kommas hintereinander).

**Comment by stapetz** [comment]
Moin,

Danke für die Impulse. Das Problem ist, dass es beim Dummy Device kein „GET“ gibt. Ich muss da mit jsonlist2 arbeiten und dann das Parsing in deinem Widget anpassen.

Dein Tipp mit get virtualSolar json zeigt dann nämlich genau die Meldung: "No get implemented for virtualSolar"

Danke für die Tipps und liebe Grüße,
Stefan
